"""add patients appointments doctors tables and user cedula username

Revision ID: 1fbb33d57c3b
Revises: 5926bb76aef3
Create Date: 2026-03-24 23:21:44.666890

Checklist antes de aplicar:
- [ ] CREATE TABLE: orden id → fk_* → datos → table_status → status → auditoría
- [ ] ALTER TABLE: modelo Python actualizado con columna en grupo correcto
- [ ] Columnas NOT NULL tienen server_default si la tabla tiene datos
- [ ] downgrade() revierte los cambios correctamente
- [ ] Columnas de auditoría/status NO fueron modificadas ni eliminadas

Ver: docs/06-estandar-base-de-datos.md
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1fbb33d57c3b'
down_revision: Union[str, None] = '5926bb76aef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Secuencia para NHM auto-incremental (pacientes)
    op.execute("CREATE SEQUENCE IF NOT EXISTS nhm_seq START 1000")

    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_holder_patient_id', sa.String(length=36), nullable=True),
    sa.Column('nhm', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('marital_status', sa.String(length=30), nullable=True),
    sa.Column('religion', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('home_address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('current_occupation', sa.String(length=255), nullable=True),
    sa.Column('work_address', sa.Text(), nullable=True),
    sa.Column('economic_classification', sa.String(length=30), nullable=True),
    sa.Column('university_relation', sa.String(length=30), nullable=False),
    sa.Column('family_relationship', sa.String(length=30), nullable=True),
    sa.Column('medical_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_new', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('patient_status', sa.String(length=30), nullable=True),
    sa.Column('status', postgresql.ENUM('A', 'I', 'T', name='record_status', create_type=False), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_cedula'), ['cedula'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_fk_holder_patient_id'), ['fk_holder_patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_nhm'), ['nhm'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_status'), ['status'], unique=False)

    op.create_table('specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('A', 'I', 'T', name='record_status', create_type=False), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialties')),
    sa.UniqueConstraint('name', name=op.f('uq_specialties_name'))
    )
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialties_status'), ['status'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_user_id', sa.String(length=36), nullable=False),
    sa.Column('fk_specialty_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('doctor_status', sa.String(length=30), nullable=False),
    sa.Column('status', postgresql.ENUM('A', 'I', 'T', name='record_status', create_type=False), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.ForeignKeyConstraint(['fk_specialty_id'], ['specialties.id'], name=op.f('fk_doctors_fk_specialty_id_specialties')),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], name=op.f('fk_doctors_fk_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctors'))
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_fk_specialty_id'), ['fk_specialty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctors_fk_user_id'), ['fk_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctors_status'), ['status'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_patient_id', sa.String(length=36), nullable=False),
    sa.Column('fk_doctor_id', sa.String(length=36), nullable=False),
    sa.Column('fk_specialty_id', sa.String(length=36), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_first_visit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('appointment_status', sa.String(length=30), nullable=False),
    sa.Column('status', postgresql.ENUM('A', 'I', 'T', name='record_status', create_type=False), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.ForeignKeyConstraint(['fk_doctor_id'], ['doctors.id'], name=op.f('fk_appointments_fk_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['fk_patient_id'], ['patients.id'], name=op.f('fk_appointments_fk_patient_id_patients')),
    sa.ForeignKeyConstraint(['fk_specialty_id'], ['specialties.id'], name=op.f('fk_appointments_fk_specialty_id_specialties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_appointment_date'), ['appointment_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_appointment_status'), ['appointment_status'], unique=False)
        batch_op.create_index('ix_appointments_date_doctor', ['appointment_date', 'fk_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_fk_doctor_id'), ['fk_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_fk_patient_id'), ['fk_patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_fk_specialty_id'), ['fk_specialty_id'], unique=False)
        batch_op.create_index('ix_appointments_patient_status', ['fk_patient_id', 'appointment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_status'), ['status'], unique=False)

    op.create_table('doctor_availability',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_doctor_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM('A', 'I', 'T', name='record_status', create_type=False), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.ForeignKeyConstraint(['fk_doctor_id'], ['doctors.id'], name=op.f('fk_doctor_availability_fk_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_availability'))
    )
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.create_index('ix_doctor_availability_doctor_day', ['fk_doctor_id', 'day_of_week'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_availability_fk_doctor_id'), ['fk_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_availability_status'), ['status'], unique=False)

    op.create_table('doctor_exceptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_doctor_id', sa.String(length=36), nullable=False),
    sa.Column('exception_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', postgresql.ENUM('A', 'I', 'T', name='record_status', create_type=False), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.ForeignKeyConstraint(['fk_doctor_id'], ['doctors.id'], name=op.f('fk_doctor_exceptions_fk_doctor_id_doctors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_exceptions'))
    )
    with op.batch_alter_table('doctor_exceptions', schema=None) as batch_op:
        batch_op.create_index('ix_doctor_exceptions_doctor_date', ['fk_doctor_id', 'exception_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_exceptions_fk_doctor_id'), ['fk_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_exceptions_status'), ['status'], unique=False)

    op.create_table('medical_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_appointment_id', sa.String(length=36), nullable=False),
    sa.Column('fk_patient_id', sa.String(length=36), nullable=False),
    sa.Column('fk_doctor_id', sa.String(length=36), nullable=False),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_prepared', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prepared_by', sa.String(length=36), nullable=True),
    sa.Column('status', postgresql.ENUM('A', 'I', 'T', name='record_status', create_type=False), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.ForeignKeyConstraint(['fk_appointment_id'], ['appointments.id'], name=op.f('fk_medical_records_fk_appointment_id_appointments')),
    sa.ForeignKeyConstraint(['fk_doctor_id'], ['doctors.id'], name=op.f('fk_medical_records_fk_doctor_id_doctors')),
    sa.ForeignKeyConstraint(['fk_patient_id'], ['patients.id'], name=op.f('fk_medical_records_fk_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_records'))
    )
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_records_fk_appointment_id'), ['fk_appointment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_medical_records_fk_doctor_id'), ['fk_doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_fk_patient_id'), ['fk_patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_records_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cedula', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_cedula'), ['cedula'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_cedula'))
        batch_op.drop_column('username')
        batch_op.drop_column('cedula')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_records_status'))
        batch_op.drop_index(batch_op.f('ix_medical_records_fk_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_fk_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_medical_records_fk_appointment_id'))

    op.drop_table('medical_records')
    with op.batch_alter_table('doctor_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_exceptions_status'))
        batch_op.drop_index(batch_op.f('ix_doctor_exceptions_fk_doctor_id'))
        batch_op.drop_index('ix_doctor_exceptions_doctor_date')

    op.drop_table('doctor_exceptions')
    with op.batch_alter_table('doctor_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_availability_status'))
        batch_op.drop_index(batch_op.f('ix_doctor_availability_fk_doctor_id'))
        batch_op.drop_index('ix_doctor_availability_doctor_day')

    op.drop_table('doctor_availability')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_status'))
        batch_op.drop_index('ix_appointments_patient_status')
        batch_op.drop_index(batch_op.f('ix_appointments_fk_specialty_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_fk_patient_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_fk_doctor_id'))
        batch_op.drop_index('ix_appointments_date_doctor')
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_status'))
        batch_op.drop_index(batch_op.f('ix_appointments_appointment_date'))

    op.drop_table('appointments')
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_status'))
        batch_op.drop_index(batch_op.f('ix_doctors_fk_user_id'))
        batch_op.drop_index(batch_op.f('ix_doctors_fk_specialty_id'))

    op.drop_table('doctors')
    with op.batch_alter_table('specialties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialties_status'))

    op.drop_table('specialties')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_status'))
        batch_op.drop_index(batch_op.f('ix_patients_nhm'))
        batch_op.drop_index(batch_op.f('ix_patients_fk_holder_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patients_cedula'))

    op.drop_table('patients')

    op.execute("DROP SEQUENCE IF EXISTS nhm_seq")
    # ### end Alembic commands ###
