"""add auth tables users roles permissions user_roles role_permissions

Revision ID: 5926bb76aef3
Revises: 
Create Date: 2026-03-24 17:10:28.870350

Checklist antes de aplicar:
- [ ] CREATE TABLE: orden id → fk_* → datos → table_status → status → auditoría
- [ ] ALTER TABLE: modelo Python actualizado con columna en grupo correcto
- [ ] Columnas NOT NULL tienen server_default si la tabla tiene datos
- [ ] downgrade() revierte los cambios correctamente
- [ ] Columnas de auditoría/status NO fueron modificadas ni eliminadas

Ver: docs/06-estandar-base-de-datos.md
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5926bb76aef3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('A', 'I', 'T', name='record_status'), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_permissions_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_status'), ['status'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('A', 'I', 'T', name='record_status'), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_roles_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_auth', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Proveedores externos: {"auth0": {"sub": "..."}, "keycloak": {"sub": "..."}}'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('user_status', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('A', 'I', 'T', name='record_status'), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_role_id', sa.String(length=36), nullable=False),
    sa.Column('fk_permission_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('A', 'I', 'T', name='record_status'), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.ForeignKeyConstraint(['fk_permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_fk_permission_id_permissions')),
    sa.ForeignKeyConstraint(['fk_role_id'], ['roles.id'], name=op.f('fk_role_permissions_fk_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('fk_role_id', 'fk_permission_id', name='uq_role_permissions_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_fk_permission_id'), ['fk_permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_fk_role_id'), ['fk_role_id'], unique=False)
        batch_op.create_index('ix_role_permissions_role_status', ['fk_role_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_status'), ['status'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fk_user_id', sa.String(length=36), nullable=False),
    sa.Column('fk_role_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('A', 'I', 'T', name='record_status'), server_default='A', nullable=False, comment='Status técnico: A=active, I=inactive, T=trash'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True, comment='UUID del usuario que creó el registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True, comment='UUID del usuario que actualizó el registro'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='UUID del usuario que eliminó (soft-delete) el registro'),
    sa.ForeignKeyConstraint(['fk_role_id'], ['roles.id'], name=op.f('fk_user_roles_fk_role_id_roles')),
    sa.ForeignKeyConstraint(['fk_user_id'], ['users.id'], name=op.f('fk_user_roles_fk_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('fk_user_id', 'fk_role_id', name='uq_user_roles_user_role')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_fk_role_id'), ['fk_role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_fk_user_id'), ['fk_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_status'), ['status'], unique=False)
        batch_op.create_index('ix_user_roles_user_status', ['fk_user_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('ix_user_roles_user_status')
        batch_op.drop_index(batch_op.f('ix_user_roles_status'))
        batch_op.drop_index(batch_op.f('ix_user_roles_fk_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_fk_role_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_status'))
        batch_op.drop_index('ix_role_permissions_role_status')
        batch_op.drop_index(batch_op.f('ix_role_permissions_fk_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_fk_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_status'))
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_status'))
        batch_op.drop_index(batch_op.f('ix_permissions_module'))
        batch_op.drop_index(batch_op.f('ix_permissions_code'))

    op.drop_table('permissions')
    # ### end Alembic commands ###
